# QUICKSTART:
# Copy this file to .secrets.toml in the same folder.
# The minimum workable settings - set openai.key to your API key.
# Set github.deployment_type to "user" and github.user_token to your GitHub personal access token.
# This will allow you to run the CLI scripts in the scripts/ folder and the github_polling server.
#
# See README for details about GitHub App deployment.

[openai]
key = ""  # Acquire through https://platform.openai.com
#org = "<ORGANIZATION>"  # Optional, may be commented out.
# Uncomment the following for Azure OpenAI
#api_type = "azure"
#api_version = '2023-05-15'  # Check Azure documentation for the current API version
#api_base = ""  # The base URL for your Azure OpenAI resource. e.g. "https://<your resource name>.openai.azure.com"
#deployment_id = ""  # The deployment name you chose when you deployed the engine
#fallback_deployments = []  # For each fallback model specified in configuration.toml in the [config] section, specify the appropriate deployment_id

[pinecone]
api_key = "..."
environment = "gcp-starter"

[anthropic]
key = "" # Optional, uncomment if you want to use Anthropic. Acquire through https://www.anthropic.com/

[cohere]
key = "" # Optional, uncomment if you want to use Cohere. Acquire through https://dashboard.cohere.ai/

[replicate]
key = "" # Optional, uncomment if you want to use Replicate. Acquire through https://replicate.com/

[groq]
key = "" # Acquire through https://console.groq.com/keys

[huggingface]
key = "" # Optional, uncomment if you want to use Huggingface Inference API. Acquire through https://huggingface.co/docs/api-inference/quicktour
api_base = "" # the base url for your huggingface inference endpoint

[ollama]
api_base = "" # the base url for your local Llama 2, Code Llama, and other models inference endpoint. Acquire through https://ollama.ai/

[vertexai]
vertex_project = "" # the google cloud platform project name for your vertexai deployment
vertex_location = "" # the google cloud platform location for your vertexai deployment

[google_ai_studio]
gemini_api_key = "" # the google AI Studio API key

[github]
# ---- Set the following only for deployment type == "user"
user_token = ""  # A GitHub personal access token with 'repo' scope.
deployment_type = "user" #set to user by default

# ---- Set the following only for deployment type == "app", see README for details.
private_key = """\
-----BEGIN RSA PRIVATE KEY-----
MIIEpAIBAAKCAQEAwLGW8s9VUz0gWvHAeNheNBGdkaA3mLU3tGx5kRWG57A0Smxk
PCian25PEjk3uB9Zu+5Ng1cOpUBgkP7BCrTMRKzjGYxMVKDhwLaUpee/fTEg9ZQl
cLXF3phSWJ89xMzUV0fklhh0UYT3ls73+RSTacTZBqSxXbjmIY8OtwZG9y3zaLsf
1Lo2YnEJRCaxEDJ5HdqdwzZwPO1uDBfv/nYlRqJFdH48aM0+u3RBRM/rZVT33KHG
QWDbHpuhxR0LQHMbCcKaAsav130B79fRIWrxdpxVCvgUALB0LvYDqWrFn5typG64
zxrqMAr3dU/K0M3ohEEJOy9XOnA/jW5tAe/+zwIDAQABAoIBAE4rPMr/ZOPBllCO
ZcAgNgb1ZnBfCG7AhPqCTsaWbwWqK2xNkFP/PMqUWytPXtUokqR0RamUNXLALOxl
DDalpX/uiqogig6CvVIKPz8WRk4pEe/Ny2pvsvdb33voDYy6cyF9HrPs87LmN/JL
v7ihqjNsEYZqZTFaArF2cUe6GivHGhTg0O5xZSWvjfmsi5+zGUxPvnhZ+KuQc7D6
DfJ2tPM5EBNerlzSL6o0z+MTMH0AifE+yg+N8RslPDIuqIWGHshiVR4B/GhLnHNo
yYF1kWTNmlP1ZasEGK4mbdqMhoZsPJEld0JHeXORNWStExU6Y/wLHOTT7RRlzKAc
zjZiY6ECgYEA35Wtv02FI/3r1/3uH7ZsZInva7JF594GbY6PMs28yhcJkiiHF1Jb
vn0xW/QGnNxw5Fw7tm1G30Gglf871rQu2Sy0ZOewEFlX1bx3XErAhrYlKA49mi7s
l8M5kkXbcBPCAGky0oLq4R3uzpt7QNQwgWBmQ0Fw+Ny3fM4rE1RKeWcCgYEA3KFl
VNOGTp9ATxfwOKURCwz3UhxpyscUJoL8lnnrGx1IIW4385RZOxovngq25mw5iQR7
6Em7HH7Xz0nUPNiyS8bSG3NWnTyg4Wk67ri/TdKFKmQ+g5k+juxZ79k0dp9ybJ0p
cj/zmwnNp1cZxlbYSHAvCdecL6R31M/tTSE1plkCgYEAygpiBZsxkwKkGnyWsAWT
EY8r0XA5h3u050+Jy2jrDtuehHsnCEYeLZbIAcYUK69wPIu0UfeRsbGGQcVw92W/
Z/Tj1sMe8McrfjNe0QGj1JfIH9guhqOcnM+HuMxzrWXNS73EdUJkqaT45a7OxBh6
9I5+GoyKX/hjvt43QrJK0kUCgYEAz/ZZm2FegZFefq8jwWDl9bKdFQqvNXH9Lmfd
SsFUuNQa/1fy6Wf1y93c8G1NBVkRynMtkECfXDa7mSoQIeJn/UFFHpbTF5bkVlRo
NkhyGhrLZq/itQyniPSDua7U4tNcecCSJpzdNFBDRu603t1RNMZ5sB9Jmya9xRzQ
oxkghtECgYA09lRXO69MEEiZMgq0ckPfELjOoKwtJPbKI4uIZ0sFgPwqLnzNzag7
peqsoDXrvn7HujRCnJ6nxP2kT8m4Csq3hs+3GQMncCTragcsKKMNd0PXaG5EMtMN
m0TC0RE/692qf/KOdW50dxYqswUGT3HaA8fWr23gfxF5P/2QGUfD9Q==
-----END RSA PRIVATE KEY-----
"""
app_id = 123456  # The GitHub App ID, replace with your own.
webhook_secret = "<WEBHOOK SECRET>"  # Optional, may be commented out.

[gitlab]
# Gitlab personal access token
personal_access_token = ""
shared_secret = ""  # webhook secret

[bitbucket]
# For Bitbucket personal/repository bearer token
bearer_token = ""

[bitbucket_server]
# For Bitbucket Server bearer token
bearer_token = ""
webhook_secret = ""

# For Bitbucket app
app_key = ""
base_url = ""

[litellm]
LITELLM_TOKEN = "" # see https://docs.litellm.ai/docs/debugging/hosted_debugging for details and instructions on how to get a token

[azure_devops]
# For Azure devops personal access token
org = ""
pat = ""

[azure_devops_server]
# For Azure devops Server basic auth - configured in the webhook creation
# Optional, uncomment if you want to use Azure devops webhooks. Value assinged when you create the webhook
# webhook_username = "<basic auth user>"
# webhook_password = "<basic auth password>"
